#!/usr/bin/env bash
set -e


# Default values for input arguments
WHALES=2
FISH=1
NODES=1
ARCHIVE=false
LOG_LEVEL="Trace"
FILE_LOG_LEVEL=${LOG_LEVEL}
VALUE_TRANSFERS=false
SNARK_WORKERS_COUNT=1
ZKAPP_TRANSACTIONS=false
RESET=false
UPDATE_GENESIS_TIMESTAMP=true
PROOF_LEVEL="full"

SNARK_WORKER_FEE=0.001
TRANSACTION_FREQUENCY=10 # in seconds

SEED_START_PORT=3000
ARCHIVE_SERVER_PORT=3086
SNARK_COORDINATOR_PORT=7000
WHALE_START_PORT=4000
FISH_START_PORT=5000
NODE_START_PORT=6000

PG_HOST="localhost"
PG_PORT="5432"
PG_USER="${PG_USER:-postgres}"
PG_PASSWD=""
PG_DB="${PG_DB:-archive}"
PG_SCHEMA_PATH="${PG_SCHEMA_PATH:-/mina/create_schema.sql}"

ARCHIVE_ADDRESS_CLI_ARG=""

MINA_EXE="${MINA_EXE:-/usr/local/bin/mina}"
ARCHIVE_EXE="${ARCHIVE_EXE:-/usr/local/bin/archive}"
LOGPROC_EXE="${LOGPROC_EXE:-/usr/local/bin/logproc}"
ZKAPP_EXE="${ZKAPP_EXE:-/usr/local/bin/zkapp_test_transaction}"

export MINA_PRIVKEY_PASS="${MINA_PRIVKEY_PASS:-naughty blue worm}"
export MINA_LIBP2P_PASS="${MINA_PRIVKEY_PASS}"

# Globals (assigned during execution of script)
LEDGER_FOLDER=""
SNARK_COORDINATOR_PUBKEY=""
NODES_FOLDER=""
CONFIG=${LEDGER_FOLDER}/daemon.json
SNARK_COORDINATOR_PID=""
SEED_PID=""
ARCHIVE_PID=""
WHALE_PIDS=()
SNARK_WORKERS_PIDS=()
FISH_PIDS=()
NODE_PIDS=()
